version: '3.8'

services:
    mongo:
        image: mongo:latest
        volumes:
            - mongo_data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - '27017:27017'
        networks:
            - app-network

    backend:
        build:
            context: ./backend
        ports:
            - '5000:5000'
        environment:
            MONGO_URI: 'mongodb://root:password@mongo:27017/tasks?authSource=admin'
        depends_on:
            - mongo    
        networks:
            - app-network

    frontend:
        build:
            context: ./frontend
        environment:
            - VITE_API_URL=http://backend:5000
        ports:
            - '3000:80'
        depends_on:
            - backend
        networks:
            - app-network

volumes:
    mongo_data:

networks:
    app-network:
        driver: bridge
